config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # get '/', to: "welcome#index" 
  # root "welcome#index"
  root "items#index"
  #users
  get '/login', to: "users#login"
  post '/login', to: "users#sign_in"
  delete 'logout', to: "users#logout"
  get '/sign_up', to: "users#signup"
  post '/sign_up', to: "users#registration"
  
  #items
  resources :items do
    resources :comments, only:[:create]
  end

  #API
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
      end
    end
  end
  
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
          <a class="nav-link" href="#">2020 &COPY; Joseph Hung</a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">BxLunch Group</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "餐點列表", items_path, class: 'nav-link' %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "我要開團", '#' , class: 'nav-link'%>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= current_user.email %> |</a>
        </li>
        <li class="nav-item">
          <%= link_to "登出", logout_path, class: 'nav-link', method: 'delete' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="sign_up">註冊</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">登入</a>
        </li>   
      <% end %>
    </ul>
  </div>
</nav>