config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # get '/', to: "welcome#index" 
  # root "welcome#index"
  root "items#index"
  #users
  get '/login', to: "users#login"
  post '/login', to: "users#sign_in"
  delete 'logout', to: "users#logout"
  get '/sign_up', to: "users#signup"
  post '/sign_up', to: "users#registration"
  
  #items
  resources :items do
    resources :comments, only:[:create]
  end

  #API
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
      end
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 } 
                    
  belongs_to :category
  has_one_attached :cover
  has_many :comments
  
  has_many :favorite_items
  has_many :users, through: :favorite_items

  # scope :available, -> { where(deleted_at: nil)}
  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
  def favorited_by(u)
    u.items.include?(self)
  end
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :check_login
  def favorite
    item = Item.find(params[:id]) 
    if item.favorited_by(current_user)
      current_user.items.delete(item)
      render json: {status: 'removed'}
    else
      current_user.items << item
      render json: {status: 'favorited'}
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: '餐點新增成功！'
    else
     render :new
    end
  end
  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end
  def edit
    
  end
  def update
    if @item.update(item_params)
      redirect_to items_path, notice: "餐點更新成功！"
    else
      render :edit
    end
  end
  def destroy
    @item.destroy
    # @item.update(deleted_at: Time.now)
    redirect_to items_path, alert: "餐點已刪除！"
  end

  private
  def item_params
    params.require(:item).permit(:name,
                                 :price,
                                 :category_id,
                                 :description,
                                 :cover,
                                 :spec)
  end
  def find_item
    @item = Item.find(params[:id])
  end

end

app/helpers/api/v1/items_helper.rb
module Api::V1::ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %> 
  <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  
  <div>
    <%= f.label :cover%>
    <%= f.file_field :cover%>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>編輯餐點</h1>
<%= render "form", item: @item %>

app/views/items/index.html.erb
<h1>餐點列表</h1>
<%= link_to "新增", new_item_path %>

<div class="container">
  <div class="row">
    <% @items.each do |item|%>
    <div class="col-12 col-md-4">
      <div class="card mt-3">
        <div class="overflow-hidden food-cover">
          <%= image_tag item.cover.variant(resize_to_limit: [500, 500]) if item.cover.attached? %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to item.name, item_path(item.id) %></h5>
          <p class="card-text"><%= item.category.name %></p>
          <%= link_to "編輯", edit_item_path(item.id), class: 'btn btn-info' %>
          <%= link_to "刪除", item_path(item.id), class: 'btn btn-danger', 
                                                  method: "delete", 
                                                  data: { confirm: "確定要刪除餐點？？"} %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<h1>新增餐點</h1>
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<h2 data-controller="item">
  <%= @item.name %>
  <a href="#" class="btn btn-danger" data-action="item#heart">
    <i class="far fa-heart" data-target="item.icon"></i>
  </a>
</h2>
<%= image_tag @item.cover.variant(resize_to_limit: [500, 500]) if @item.cover.attached? %>
<h5>價格：$<%= @item.price %>元</h5>

<div data-controller="comment">
  <h5>留言區</h5>
  <%= form_for(@comment, url: item_comments_path(@item), remote: true) do |form| %>
    <input type="hidden" id="item_id" value="<%= @item.id %>">
    <div class="form-group">
      <%= form.text_area :content, 
                         class: 'form-control',
                         data: {target: 'comment.content',
                         action: 'keyup->comment#check'} %>
    </div>
  <%= form.submit class: 'btn btn-outline-secondary', disabled: true, data: {target: 'comment.submit'}  %>
  <% end %>
  <hr>
</div>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>





<!--
<% @comments.each do |comment| %>
  <div class="card">
    <div class="card-header">
      Featured
    </div>
    <div class="card-body">
        <p class="card-text"><%= comment.content %></p>
    </div>
  </div>
<% end %>
-->